import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Download, Copy, Check, Smartphone, Globe, RefreshCw } from "lucide-react";

interface ManifestData {
  name: string;
  short_name: string;
  description: string;
  start_url: string;
  display: string;
  background_color: string;
  theme_color: string;
  orientation: string;
  lang: string;
  categories: string;
  scope: string;
}

const DISPLAY_MODES = ["standalone", "fullscreen", "minimal-ui", "browser"];
const ORIENTATIONS = ["any", "portrait", "landscape", "portrait-primary", "landscape-primary"];
const ICON_SIZES = [72, 96, 128, 144, 152, 192, 256, 384, 512];

function generateServiceWorker(manifest: ManifestData): string {
  return `// Service Worker generated by ToolNames PWA Generator
// Cache name - update version to force refresh
const CACHE_NAME = '${manifest.short_name.replace(/\s+/g, '-').toLowerCase()}-v1';

// Files to cache on install
const STATIC_ASSETS = [
  '/',
  '/index.html',
  '/manifest.json',
  // Add your CSS, JS, image files here
];

// Install event - cache static assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[SW] Caching static assets');
      return cache.addAll(STATIC_ASSETS);
    })
  );
  self.skipWaiting();
});

// Activate event - clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      )
    )
  );
  self.clients.claim();
});

// Fetch event - serve from cache, fallback to network
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      if (cachedResponse) return cachedResponse;
      return fetch(event.request).then((response) => {
        if (!response || response.status !== 200 || response.type !== 'basic') {
          return response;
        }
        const responseToCache = response.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseToCache);
        });
        return response;
      });
    })
  );
});
`;
}

function generateHTMLSnippet(manifest: ManifestData): string {
  return `<!-- PWA Meta Tags - Add to your <head> -->
<meta name="application-name" content="${manifest.name}" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="default" />
<meta name="apple-mobile-web-app-title" content="${manifest.short_name}" />
<meta name="description" content="${manifest.description}" />
<meta name="theme-color" content="${manifest.theme_color}" />
<meta name="msapplication-TileColor" content="${manifest.background_color}" />

<!-- Manifest link -->
<link rel="manifest" href="/manifest.json" />

<!-- Apple Touch Icons -->
<link rel="apple-touch-icon" sizes="152x152" href="/icons/icon-152.png" />
<link rel="apple-touch-icon" sizes="192x192" href="/icons/icon-192.png" />

<!-- Register Service Worker -->
<script>
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('/sw.js')
        .then(reg => console.log('SW registered:', reg.scope))
        .catch(err => console.error('SW registration failed:', err));
    });
  }
</script>`;
}

export const PWAManifestGenerator = () => {
  const [manifest, setManifest] = useState<ManifestData>({
    name: "My Awesome App",
    short_name: "MyApp",
    description: "An amazing progressive web app",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#3b82f6",
    orientation: "any",
    lang: "en",
    categories: "utilities",
    scope: "/",
  });
  const [copied, setCopied] = useState("");

  const updateField = (key: keyof ManifestData, value: string) => {
    setManifest(prev => ({ ...prev, [key]: value }));
  };

  const generateManifest = () => {
    const icons = ICON_SIZES.map(size => ({
      src: `/icons/icon-${size}.png`,
      sizes: `${size}x${size}`,
      type: "image/png",
      purpose: size >= 192 ? "any maskable" : "any",
    }));

    return {
      name: manifest.name,
      short_name: manifest.short_name,
      description: manifest.description,
      start_url: manifest.start_url,
      scope: manifest.scope,
      display: manifest.display,
      background_color: manifest.background_color,
      theme_color: manifest.theme_color,
      orientation: manifest.orientation,
      lang: manifest.lang,
      categories: manifest.categories.split(",").map(c => c.trim()).filter(Boolean),
      icons,
      shortcuts: [
        {
          name: "Open App",
          short_name: "Open",
          description: "Open the main app",
          url: "/",
          icons: [{ src: "/icons/icon-96.png", sizes: "96x96" }],
        },
      ],
    };
  };

  const manifestJSON = JSON.stringify(generateManifest(), null, 2);

  const copyText = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id); setTimeout(() => setCopied(""), 2000);
  };

  const downloadFile = (content: string, filename: string, type = "application/json") => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = filename; a.click();
    URL.revokeObjectURL(url);
  };

  const score = () => {
    let s = 0;
    if (manifest.name) s += 20;
    if (manifest.short_name) s += 10;
    if (manifest.description) s += 10;
    if (manifest.start_url) s += 10;
    if (manifest.theme_color !== "#ffffff") s += 10;
    if (manifest.background_color) s += 10;
    if (manifest.display !== "browser") s += 10;
    if (manifest.categories) s += 10;
    if (manifest.lang) s += 10;
    return s;
  };

  const pwaScore = score();

  return (
    <Card className="w-full max-w-4xl mx-auto">
      <CardHeader>
        <div className="flex items-center gap-2">
          <Smartphone className="h-6 w-6 text-primary" />
          <div>
            <CardTitle className="text-2xl">PWA Manifest Generator</CardTitle>
            <CardDescription>Generate manifest.json, service worker, and meta tags for Progressive Web Apps</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-5">
        <Tabs defaultValue="config">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="config">Config</TabsTrigger>
            <TabsTrigger value="manifest">manifest.json</TabsTrigger>
            <TabsTrigger value="sw">Service Worker</TabsTrigger>
            <TabsTrigger value="html">HTML Snippet</TabsTrigger>
          </TabsList>

          <TabsContent value="config" className="mt-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-3">
                <div><Label>App Name *</Label>
                  <Input value={manifest.name} onChange={e => updateField("name", e.target.value)} placeholder="My Awesome App" /></div>
                <div><Label>Short Name (max 12 chars) *</Label>
                  <Input value={manifest.short_name} onChange={e => updateField("short_name", e.target.value.slice(0, 12))} placeholder="MyApp" /></div>
                <div><Label>Description</Label>
                  <Input value={manifest.description} onChange={e => updateField("description", e.target.value)} /></div>
                <div><Label>Start URL</Label>
                  <Input value={manifest.start_url} onChange={e => updateField("start_url", e.target.value)} placeholder="/" /></div>
                <div><Label>Scope</Label>
                  <Input value={manifest.scope} onChange={e => updateField("scope", e.target.value)} placeholder="/" /></div>
              </div>

              <div className="space-y-3">
                <div><Label>Display Mode</Label>
                  <Select value={manifest.display} onValueChange={v => updateField("display", v)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>{DISPLAY_MODES.map(m => <SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent>
                  </Select></div>
                <div><Label>Orientation</Label>
                  <Select value={manifest.orientation} onValueChange={v => updateField("orientation", v)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>{ORIENTATIONS.map(o => <SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent>
                  </Select></div>
                <div><Label>Theme Color</Label>
                  <div className="flex gap-2">
                    <input type="color" value={manifest.theme_color} onChange={e => updateField("theme_color", e.target.value)} className="h-9 w-12 rounded border cursor-pointer" />
                    <Input value={manifest.theme_color} onChange={e => updateField("theme_color", e.target.value)} className="flex-1 font-mono" />
                  </div></div>
                <div><Label>Background Color</Label>
                  <div className="flex gap-2">
                    <input type="color" value={manifest.background_color} onChange={e => updateField("background_color", e.target.value)} className="h-9 w-12 rounded border cursor-pointer" />
                    <Input value={manifest.background_color} onChange={e => updateField("background_color", e.target.value)} className="flex-1 font-mono" />
                  </div></div>
                <div><Label>Language</Label>
                  <Input value={manifest.lang} onChange={e => updateField("lang", e.target.value)} placeholder="en" /></div>
                <div><Label>Categories (comma separated)</Label>
                  <Input value={manifest.categories} onChange={e => updateField("categories", e.target.value)} placeholder="utilities, productivity" /></div>
              </div>
            </div>

            {/* PWA Score */}
            <div className="mt-4 border rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <Globe className="h-4 w-4" />
                  <span className="font-medium">PWA Completeness Score</span>
                </div>
                <span className={`text-xl font-bold ${pwaScore >= 80 ? "text-green-500" : pwaScore >= 50 ? "text-yellow-500" : "text-red-500"}`}>
                  {pwaScore}/100
                </span>
              </div>
              <div className="bg-muted rounded-full h-3">
                <div className={`h-3 rounded-full transition-all ${pwaScore >= 80 ? "bg-green-500" : pwaScore >= 50 ? "bg-yellow-500" : "bg-red-500"}`}
                  style={{ width: `${pwaScore}%` }} />
              </div>
            </div>
          </TabsContent>

          <TabsContent value="manifest" className="mt-4">
            <div className="flex gap-2 mb-3">
              <Button size="sm" onClick={() => copyText(manifestJSON, "manifest")}>
                {copied === "manifest" ? <Check className="h-3 w-3 mr-1" /> : <Copy className="h-3 w-3 mr-1" />}Copy
              </Button>
              <Button size="sm" variant="outline" onClick={() => downloadFile(manifestJSON, "manifest.json")}>
                <Download className="h-3 w-3 mr-1" />Download
              </Button>
            </div>
            <pre className="bg-muted rounded-lg p-4 text-xs font-mono overflow-auto max-h-[500px]">{manifestJSON}</pre>
          </TabsContent>

          <TabsContent value="sw" className="mt-4">
            <div className="flex gap-2 mb-3">
              <Button size="sm" onClick={() => copyText(generateServiceWorker(manifest), "sw")}>
                {copied === "sw" ? <Check className="h-3 w-3 mr-1" /> : <Copy className="h-3 w-3 mr-1" />}Copy
              </Button>
              <Button size="sm" variant="outline" onClick={() => downloadFile(generateServiceWorker(manifest), "sw.js", "application/javascript")}>
                <Download className="h-3 w-3 mr-1" />Download sw.js
              </Button>
            </div>
            <pre className="bg-muted rounded-lg p-4 text-xs font-mono overflow-auto max-h-[500px]">{generateServiceWorker(manifest)}</pre>
          </TabsContent>

          <TabsContent value="html" className="mt-4">
            <div className="flex gap-2 mb-3">
              <Button size="sm" onClick={() => copyText(generateHTMLSnippet(manifest), "html")}>
                {copied === "html" ? <Check className="h-3 w-3 mr-1" /> : <Copy className="h-3 w-3 mr-1" />}Copy
              </Button>
              <Button size="sm" variant="outline" onClick={() => downloadFile(generateHTMLSnippet(manifest), "pwa-meta.html", "text/html")}>
                <Download className="h-3 w-3 mr-1" />Download
              </Button>
            </div>
            <pre className="bg-muted rounded-lg p-4 text-xs font-mono overflow-auto max-h-[500px]">{generateHTMLSnippet(manifest)}</pre>
          </TabsContent>
        </Tabs>

        <div className="bg-muted rounded-lg p-3 text-sm text-muted-foreground">
          <strong>PWA APIs</strong> — Generates <code>manifest.json</code> (Web App Manifest), Service Worker (Cache API + Background Sync), and HTML meta tags for a production-ready PWA.
        </div>
      </CardContent>
    </Card>
  );
};
