import React, { useState, useMemo } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Leaf } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { LifestyleInputs } from "./LifestyleInputs";
import { CarbonResultsDisplay } from "./CarbonResults";
import { ReductionSuggestions } from "./ReductionSuggestions";
import { CarbonVisualizations } from "./CarbonVisualizations";
import {
  calculateCarbonFootprint,
  getReductionSuggestions,
  CarbonInputs,
} from "./carbonUtils";

export const CarbonFootprintCalculator: React.FC = () => {
  const [inputs, setInputs] = useState<CarbonInputs>({
    // Transportation defaults
    carKmPerYear: 12000,
    flightKmPerYear: 2000,
    transitKmPerYear: 1000,

    // Energy defaults
    electricityKwhPerMonth: 900,
    gasKwhPerMonth: 200,
    heatingOilKwhPerMonth: 0,

    // Food defaults
    meatKgPerWeek: 2,
    dairyKgPerWeek: 3,
    vegetablesKgPerWeek: 5,

    // Shopping defaults
    clothingPerMonth: 100,
    electronicsPerMonth: 50,
    otherShoppingPerMonth: 200,
  });

  const results = useMemo(() => {
    return calculateCarbonFootprint(inputs);
  }, [inputs]);

  const suggestions = useMemo(() => {
    return getReductionSuggestions(inputs);
  }, [inputs]);

  return (
    <div className="w-full max-w-7xl mx-auto p-4">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-3xl">
            <Leaf className="h-8 w-8 text-green-600" />
            Carbon Footprint Calculator
          </CardTitle>
          <CardDescription className="text-base">
            Calculate your personal carbon emissions and discover ways to reduce
            your environmental impact. Enter your lifestyle information to get
            started.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="inputs" className="w-full">
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="inputs">Inputs</TabsTrigger>
              <TabsTrigger value="results">Results</TabsTrigger>
              <TabsTrigger value="suggestions">Suggestions</TabsTrigger>
              <TabsTrigger value="visualizations">Charts</TabsTrigger>
            </TabsList>

            <TabsContent value="inputs" className="mt-6">
              <LifestyleInputs inputs={inputs} onChange={setInputs} />
            </TabsContent>

            <TabsContent value="results" className="mt-6">
              <CarbonResultsDisplay results={results} />
            </TabsContent>

            <TabsContent value="suggestions" className="mt-6">
              <ReductionSuggestions suggestions={suggestions} />
            </TabsContent>

            <TabsContent value="visualizations" className="mt-6">
              <CarbonVisualizations results={results} />
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {/* Information Section */}
      <Card className="mt-6">
        <CardHeader>
          <CardTitle className="text-xl">About Carbon Footprint</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="font-semibold mb-2">What is a Carbon Footprint?</h3>
            <p className="text-muted-foreground">
              A carbon footprint is the total amount of greenhouse gases
              (including carbon dioxide and methane) generated by our actions.
              The average carbon footprint for a person in the United States is
              16 tonnes per year, one of the highest rates in the world. The
              global average is approximately 4 tonnes per year.
            </p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">Why Does It Matter?</h3>
            <p className="text-muted-foreground">
              To avoid a 2°C rise in global temperatures, the average global
              carbon footprint needs to drop to under 2 tonnes by 2050.
              Understanding and reducing your carbon footprint is one of the
              most important things you can do to fight climate change.
            </p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">How to Use This Calculator</h3>
            <p className="text-muted-foreground">
              Enter your annual transportation distances, monthly energy usage,
              weekly food consumption, and monthly shopping expenses. The
              calculator will estimate your total carbon emissions and provide
              personalized suggestions for reducing your environmental impact.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
